version: '3'

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8000:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${MAIN_DOMAIN}`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.entrypoints=web,websecure
      - traefik.http.routers.portainer.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.portainer.headers.SSLRedirect=true
      - traefik.http.middlewares.portainer.headers.STSSeconds=315360000
      - traefik.http.middlewares.portainer.headers.browserXSSFilter=true
      - traefik.http.middlewares.portainer.headers.contentTypeNosniff=true
      - traefik.http.middlewares.portainer.headers.forceSTSHeader=true
      - traefik.http.middlewares.portainer.headers.SSLHost=${MAIN_DOMAIN}
      - traefik.http.middlewares.portainer.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.portainer.headers.STSPreload=true
      - traefik.http.routers.portainer.middlewares=portainer@docker
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik-network

volumes:
  portainer_data:

networks:
  traefik-network:
    external: true