version: '3'

services:
  wa:
    image: chandrabachtiar25/wa-simple:latest
    container_name: wa
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.wa.rule=Host(`wa.${MAIN_DOMAIN}`)
      - traefik.http.routers.wa.tls=true
      - traefik.http.routers.wa.entrypoints=web,websecure
      - traefik.http.routers.wa.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.wa.headers.SSLRedirect=true
      - traefik.http.middlewares.wa.headers.STSSeconds=315360000
      - traefik.http.middlewares.wa.headers.browserXSSFilter=true
      - traefik.http.middlewares.wa.headers.contentTypeNosniff=true
      - traefik.http.middlewares.wa.headers.forceSTSHeader=true
      - traefik.http.middlewares.wa.headers.SSLHost=${MAIN_DOMAIN}
      - traefik.http.middlewares.wa.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.wa.headers.STSPreload=true
      - traefik.http.routers.wa.middlewares=wa@docker
    environment:
      - PORT=3000
      - NODE_ENV=production
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - APIKEY=${APIKEY}
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true